accounts/urls.py
from django.conf.urls import url
from . import views

# specific app URL pointable from template
app_name = 'accounts'

urlpatterns = [
    url(r'^register/', views.auth_register, name="register"),
    url(r'^login/', views.auth_login, name="login"),
    url(r'^logout/', views.auth_logout, name="logout"),
    url(r'^profile/', views.auth_profile, name="profile"),
]

user_accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'user_accounts'

urlpatterns = [
    url(r'^register/', views.register, name="register"),
    url(r'^login/',views.login_view, name='login'),
    url(r'^registration_type/', views.registration_type, name="registration_type")
]

user_accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

user_accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

# Create your views here.


def register(request):
    if request.method == 'POST':
        #   IF THE PASSWORDS MATCH
        if request.POST['password1'] == request.POST['password2']:
            username = request.POST['username']
            password = request.POST['password1']
            #   CHECK IF USERNAME ALREADY EXISTS, IF NOT, THEN CREATE A NEW USER AND LOG THEM IN
            try:
                user = User.objects.get(username=username)
                return render(request,'user_accounts/register.html',{'error':'Username already in use'})
            except:
                user = User.objects.create_user(username=username,password=password)
                login(request, user)
                args = {'error': 'Account created and logged in'}
                return redirect(request,'user_accounts/register.html', args)
        else:
            args = {'error': '**Passwords do not match**'}
            return render(request,'user_accounts/register.html',args)
    else:
        #   INITIAL LOAD
        return render(request, 'user_accounts/register.html')

def login_view(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'],password=request.POST['password'])
        #   IF THE USER EXISTS, LOG THEM IN, IF NOT DISPLAY AN ERROR
        if user is not None:
            login(request,user)
            args = {'error':'Logged in successfully'}
            return render(request,'user_accounts/login.html',args)
        else:
            args = {'error':'User not found'}
            return render(request,'user_accounts/login.html',args)
    else:
        #   WHEN PAGE LOADS INITIALLY
        return render(request,'user_accounts/login.html')


def registration_type(request):
    return render(request, 'user_accounts/registered_user_type.html')

user_accounts/templates/user_accounts/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="row" >
        <div class="col-4">
            &nbsp;
        </div>
        <div class="col-4">
        <!-- CREATE FORM HERE -->
            <form action="{%  url 'user_accounts:login' %}" method="POST" id="register-form">
                {% csrf_token %}
                <div class="row registration">
                    <div class="col-4">
                        <label for="username">Username:</label>
                    </div>
                    <div class="col-8">
                        <input type="text" name="username" id="username" required>
                    </div>
                </div>
                <div class="row registration">
                    <div class="col-4">
                        <label for="password">Password:</label>
                    </div>
                    <div class="col-8">
                        <input type="password" name="password" id="password" required>
                    </div>
                </div>
                <div class="row registration">
                    <div class="col-12 text-center">
                        {% if error %}
                            <span class="orange-text">{{ error }}</span>
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <input type="submit" class="btn btn-block full_btn" value="Login" id="register-submit">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-4">
            &nbsp;&nbsp;
        </div>
    </div>

{% endblock %}
{% block script %}
    <script>
        $(document).ready(function(){
           console.log('registration loaded');
        });
    </script>
{% endblock %}

user_accounts/templates/user_accounts/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="row" >
        <div class="col-4">
            &nbsp;
        </div>
        <div class="col-4">
        <!-- CREATE FORM HERE -->
            <form action="{%  url 'register' %}" method="POST" id="register-form">
                {% csrf_token %}
                <div class="row registration">
                    <div class="col-4">
                        <label for="username">Username:</label>
                    </div>
                    <div class="col-8">
                        <input type="text" name="username" id="username" required>
                    </div>
                </div>
                <div class="row registration">
                    <div class="col-4">
                        <label for="password1">Password:</label>
                    </div>
                    <div class="col-8">
                        <input type="password" name="password1" id="password1" required>
                    </div>
                </div>
                <div class="row registration">
                    <div class="col-4">
                        <label for="password2">Confirm Password:</label>
                    </div>
                    <div class="col-8">
                        <input type="password" name="password2" id="password2" required>
                    </div>
                </div>
                <div class="row registration">
                    <div class="col-12 text-center">
                        {% if error %}
                            <span class="orange-text">{{ error }}</span>
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <input type="submit" class="btn btn-block full_btn" value="Register" id="register-submit">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-4">
            &nbsp;
        </div>
    </div>

{% endblock %}
{% block script %}
    <script>
        $(document).ready(function(){
           console.log('registration loaded');
        });
    </script>
{% endblock %}

user_accounts/templates/user_accounts/registered_user_type.html
{% extends 'base.html' %}
{% block content %}
    <div class="row registered">
        <div class="col-2">
            account id is...
        </div>
        <div class="col-8">
            <div class="card-deck">
                <div class="card">
                    <img class="card-img-top" src="#" class="img-fluid center-block img-thumbnail" style="max-height:150px;" alt="Card image cap">
                    <div class="card-body">
                        <h4 class="card-title">TITLE</h4>
                        <p class="card-text">
                            Are you an Entertainer?
                        </p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted"><a href="{% url 'entertainer_profile' entertainer.id %}">...Read More</a></small>
                    </div>
                </div>
                <div class="card">
                    <img class="card-img-top" src="#" class="img-fluid center-block img-thumbnail" style="max-height:150px;" alt="Card image cap">
                    <div class="card-body">
                        <h4 class="card-title">TITLE</h4>
                        <p class="card-text">
                            Are you arranging an Event?
                        </p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted"><a href="{% url 'user_accounts:entertainer_profile' entertainer.id %}">...Read More</a></small>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-2">
            &nbsp;
        </div>
    </div>

{% endblock %}