accounts/urls.py
from django.conf.urls import url
from . import views

# specific app URL pointable from template
app_name = 'accounts'

urlpatterns = [
    url(r'^register/', views.auth_register, name="register"),
    url(r'^login/', views.auth_login, name="login"),
    url(r'^logout/', views.auth_logout, name="logout"),
    url(r'^profile/', views.auth_profile, name="profile"),
]

entertainers/urls.py
from django.conf.urls import url
from . import views
from entertainers.views import EntertainerView

# specific app URL pointable from template
app_name = 'entertainers'

urlpatterns = [
    #   pages
    url(r'^listings/$', views.listings, name="listings"),
    url(r'^profile/(?P<entertainer_id>[0-9]+)/$', views.display_entertainer_profile, name="profile"),
    url(r'^create_profile/$', views.create_profile, name="create_profile"),
    #url(r'^edit_profile/(?P<pk>[0-9]+)$', views.edit_profile, name="edit_profile"),
    url(r'^edit_profile/(?P<pk>[0-9]+)$',views.edit_profile, name="edit_profile"),

    #   actions / voting
    url(r'^(?P<pk>[0-9]+)/like/', views.like, name="like"),
    url(r'^(?P<pk>[0-9]+)/dislike/', views.dislike, name="dislike"),

    #   URLS FOR REST API CLASS BASED VIEWS
    url(r'^api/listings/$', EntertainerView.as_view(), name="list_entertainers_api"),
    url(r'^api/listings/(?P<pk>[0-9]+)/$', EntertainerView.as_view(), name="update_entertainers_api"),
]

entertainers/forms.py
from django import forms
from entertainers.models import Entertainer


class EntertainerRegistrationForm(forms.ModelForm):


    #   constructor
    def __init__(self,user,*args,**kwargs):

           # TO DO
           # RETRIEVE THE URLS LIST FROM KWARGS
           #     _urls = kwargs.pop('_urls',None)

            #   RETRIEVE THE SEPARATE URLS OF THE IMAGES
            #if _urls is not None:
            #    self.profile_image = _urls[0]
            #    self.img1 = _urls[1]

        #_urls = kwargs.pop('_urls', None)
        #if _urls is not None:
         #   self.profile_image = _urls[0]
          #  self.image1 = _urls[1]

        self.user = user
        super(EntertainerRegistrationForm,self).__init__(*args,**kwargs)

    def save(self,commit=True):
        #   save(commit=False) prevents the form from auto saving
        #   The instance of the form is what gets saved
        instance = super(EntertainerRegistrationForm,self).save(commit=False)

        #   auto set the user instance to that provided by the view
        instance.user = self.user

        #   auto set the image instance to that provided by the view
       # instance.profile_image = self.profile_image
        #instance.image1 = self.image1


        #    TO DO
        #    AUTO SET THE USER INSTANCE TO THAT PROVIDED BY THE VIEW
        #        instance.profile_image = self.profile_image
        #        instance.img1 = self.img1

        if commit:
            instance.save()
        return instance

    #   Tell Django which model to used to create the form
    class Meta:
        model = Entertainer
        fields = ('title',
                    'description',
                    'genre',
                    'location',
                    'profile_image',
                    'image1',
                    'image2',
                    'image3',
                    'image4',
                    'image5',
                    'language',
                    'music',
                    'gig_length_from',
                    'gig_length_to',
                    'bio',
                    'set_list',
                    'influences',
                    'travel_distance',
                    'min_price',
                    'max_price',
                    'soundcloud_embed_audio',
                    'youtube_embed_video',
                  'set_up_requirements',)

entertainers/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Entertainer
from django.contrib.auth.decorators import login_required
from .forms import EntertainerRegistrationForm
from django.contrib import messages
from accounts.models import User
from django.http import HttpResponse

####################
#   API Stuff
####################
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from entertainers.serializers import EntertainerSerializer
from entertainers.models import Entertainer
from django.db.models import Q
from django.core.paginator import Paginator

##########################################
#   LOGGING
##########################################
import logging
log = logging.getLogger(__name__)

####################
#   File Storage
####################
from django.core.files.storage import FileSystemStorage
from django.conf import settings

# Create your views here.
def listings(request):
    entertainers = Entertainer.objects.all()
    args = {'entertainers': entertainers}
    return render(request, 'entertainers/listings.html',args)


#   display the detail of individual entertainers
def display_entertainer_profile(request,entertainer_id):
    get = False
    if request.method == 'GET':
        get = True
    logged_in = False
    if request.user is not None:
        logged_in = True

    ######################################################################
    #   WORKAROUND FOR PAYPAL NOT RETURNING POST OR GET TO paypal_return
    #   -   WILL USE A SESSION VATIABLE TO RECORD THE ENTERTAINER THAT
    #   -   WAS BOOKED
    ######################################################################

    request.session['entertainer_id'] = entertainer_id
    #   retrieve and save the current user session
    #current_user = request.user
    #request.session['booking_user_id'] = current_user.id

    ######################################################################
    #   END WORKAROUND
    ######################################################################

    entertainer = get_object_or_404(Entertainer, pk=entertainer_id)
    user = User.objects.get(pk=entertainer.user_id)
    args = {'entertainer': entertainer,'user':user, 'get':get, 'logged_in':logged_in}
    return render(request,'entertainers/entertainer_profile.html',args)


@login_required()
def create_profile(request):
    edit = False
    profile_image = None
    image1 = None

    #if request.method == 'POST' and request.FILES['profile_image'] and request.FILES['image1']:
    if request.method == 'POST':

        #   If the form was submitted the contents of the form are passed in
        #   ALONG WITH THE LIST OF IMAGE URLS
        form = EntertainerRegistrationForm(request.user, request.POST, request.FILES)

        #   save the form if it is valid
        if form.is_valid():
            # save the currently logged in user as related to the Enterttainer profile
            #form.user = User
            form.save()
            messages.success(request, "You have successfully registered as an Entertainer")
            return redirect(reverse('entertainers:listings'))
        else:
            messages.error(request, "There was an issue and the Profile did not save")
    else:
        #   If page was just loaded then an empty form is displayed
        form = EntertainerRegistrationForm(request.user)
    return render(request, 'entertainers/create_profile.html',{'form': form,'edit':edit})


@login_required()
def edit_profile(request,pk):
    edit = True
    entertainer = None
    if request.method == 'POST':
        entertainer = Entertainer.objects.get(pk=pk)
        #   If the form was submitted the contents of the form are passed in with the entertainer instance
        form = EntertainerRegistrationForm(request.user,request.POST,request.FILES,instance=entertainer)
        #   save the form if it is valid
        if form.is_valid():
            # save the currently logged in user as related to the Enterttainer profile
            # form.user = User
            form.save()
            messages.success(request, "You have successfully registered as an Entertainer")
            return redirect(reverse('entertainers:listings'))
        else:
            messages.error(request, "There was an issue and the Profile did not save")
    else:
        entertainer=Entertainer.objects.get(pk=pk)
        form = EntertainerRegistrationForm(request.user, instance=entertainer)

    return render(request, 'entertainers/edit_profile.html', {'pk':pk, 'edit':edit, 'title':entertainer.title, 'form':form})


@login_required()
def edit_profile_old(request,pk):
    edit = True
    if request.method == 'POST':
        """
        if request.POST['id']:
            pk = request.POST['id']
        #   retrieve the entertaineredit = True
        entertainer = Entertainer.objects.get(pk=pk)
        #   If page was just loaded then an empty form is displayed
        form = EntertainerRegistrationForm(request.user,request.POST,instance=entertainer)
        """
        #form = EntertainerRegistrationForm(request.session['_auth_user_id'],request.POST, instance=entertainer)
        #form = EntertainerRegistrationForm(request.user,request.POST)
        #form.save()
    else:
        """
        #entertainer = Entertainer.objects.get(pk=pk)
        #form = EntertainerRegistrationForm(request.user,instance=entertainer)
        """
        form = EntertainerRegistrationForm(request.user)
        #return redirect(reverse('entertainers:listings'))
    return render(request, 'entertainers/create_profile.html',{'form': form,'edit':edit})


#   increment the number of likes for an entertainer
def like(request,pk):
    """
        WILL NEED TO RETRIEVE THE USER ID TO SAVE THE ENTERTAINER AS LIKED BAND
        MAYBE TRANSFER THIS TO A FAVOURITE
    """
    #   USING POST INSTEAD OF GET AS SOME BROWSERS WILL SUBMIT THE REQUEST JUST BY TYPING INTO THE URL WITH NO PRESS OF ENTER
    if request.method == 'POST':
        #   retrieve the relevant entertainer
        entertainer = Entertainer.objects.get(pk=pk)
        #   increment the number of likes
        entertainer.likes_total += 1
        #   save the entertainer record
        entertainer.save()
        #   redirect back to the same page with the like_total incremented
        return redirect('entertainers:profile',pk)


#   increment the number of likes for an entertainer
def dislike(request,pk):
    #   USING POST INSTEAD OF GET AS SOME BROWSERS WILL SUBMIT THE REQUEST JUST BY TYPING INTO THE URL WITH NO PRESS OF ENTER
    if request.method == 'POST':
        #   retrieve the relevant entertainer
        entertainer = Entertainer.objects.get(pk=pk)
        #   increment the number of likes
        entertainer.dislikes_total += 1
        #   save the entertainer record
        entertainer.save()
        #   redirect back to the same page with the dislike_total incremented
        return redirect('entertainers:profile',pk)


#   class based view for handling request coming in for REST API
class EntertainerView(APIView):
    def get(self,request,pk=None):
        """
        -   (STEP 1) Query the ORM for a list of entertainers items from the Entertainer model
        -   (STEP 2) Serialize them to JSON and retrieve from .data property
        -   (STEP 3) Return the serialized data
        :param request:
        :return: serialized entertainers items
        """
        if pk is None:
            #   'self' is necessary when using a classed based view
            description = 'all'
            location = 'all'
            page = 'all'
            recordsPerPage = 8

            if self.request.GET['description'] is not None:
                if self.request.GET['description'] != 'all':
                    description = self.request.GET['description']

            if self.request.GET['location'] is not None:
                if self.request.GET['location'] != 'all':
                    location = self.request.GET['location']

            if self.request.GET['page'] is not None:
                if self.request.GET['page'] != 'all':
                    page = self.request.GET['page']


            #   (STEP 1A)
            #   -   Need to retrieve the total number of records
            #   -   Calculate and return the number of Pages
            #   -   Return the number of records per page
            #   -   Calculate the last page count
            #   -   Add these values to the serialized data as JSON and return


            #   (STEP 1B)
            if description != 'all' and location == 'all':
                entertainers = Entertainer.objects.filter(Q(description=description))
            elif description == 'all' and location != 'all':
                entertainers = Entertainer.objects.filter(Q(location=location))
            elif description != 'all' and location != 'all':
                entertainers = Entertainer.objects.filter(Q(description=description),Q(location=location))
            elif description == 'all' and location == 'all':
                entertainers = Entertainer.objects.all()
            else:
                entertainers = Entertainer.objects.all()

            #   (STEP 1C) - ONLY RETURN DATA RELEVANT TO THE SELECTED PAGE
            if page != 'all':
                paginator = Paginator(entertainers, recordsPerPage)
                num_pages = paginator.num_pages
                count = paginator.count
                entertainers = paginator.page(int(page))
                #   (STEP 2) - CONVERT DATA TO JSON
                #serializer = EntertainerSerializer(entertainers, many=True, num_pages=num_pages, count=count)
                serializer = EntertainerSerializer(entertainers, many=True, num_pages=num_pages, count=count)
            else:

entertainers/templates/entertainers/create_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% block content %}
    {% if message %}
        {{ message }}
    {% endif %}
    <form role="form" method="post" action="{% url 'entertainers:create_profile' %}" class="account-form" enctype="multipart/form-data">
        <legend>Entertainer Profile</legend>
        <hr>
        <div class="row">
            <div class="col-1">
                &nbsp;
            </div>
            <div class="col-10">
                <div class="row">
                    {% csrf_token %}
                    {% if form %}
                        {{ form | as_bootstrap }}
                    {% endif %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-orange btn-block">Create</button>
                    </div>
                </div>
            </div>
            <div class="col-4">
                &nbsp;
            </div>
        </div>
    </form>
{% endblock %}
{% block script %}
    <script src="{% static "js/entertainer_check_menu_selections.js" %}"></script>
    <script src="{% static "js/entertainer_create.js" %}"></script>
    <script>
        $(document).ready(function(){
            $('input[type=file]').addClass('btn-orange-no-hover');
        });
    </script>
{% endblock %}

entertainers/templates/entertainers/edit_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% block content %}
    {% if message %}
        {{ message }}
    {% endif %}
    <form role="form" method="post" action="{% url 'entertainers:edit_profile' pk %}" class="account-form" enctype="multipart/form-data">
        <legend class="legend-centre brown-text">Entertainer Profile Update</legend>
        <hr>
         <div class="row">
            <div class="col-1">
                &nbsp;
            </div>
            <div class="col-10">
                <div class="row">
                    {% csrf_token %}
                    {% if form %}
                        {{ form | as_bootstrap }}
                    {% endif %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-orange btn-block">Update</button>
                    </div>
                </div>
            </div>
            <div class="col-1">
            &nbsp;
        </div>
        </div>

    </form>

{% endblock %}
{% block script %}
    <script src="{% static "js/entertainer_check_menu_selections.js" %}"></script>
    <script src="{% static "js/entertainer_update.js" %}"></script>
    <script>
        $(document).ready(function(){
            $('input[type=file]').addClass('btn-orange-no-hover');
        });
    </script>
{% endblock %}

entertainers/templates/entertainers/entertainer_details.html
{% extends 'base.html' %}
{% block content %}
    <h2>Entertainer Details</h2>
    <p>{{ entertainer_id }}</p>
{% endblock %}

entertainers/templates/entertainers/entertainers.html
{% extends 'base.html' %}
{% block content %}
    <h2>Book an Entertainer</h2>
    <p>Our very simple site</p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Description</th>
                <th>Genre</th>
                <th>Location</th>
                <th>Bio</th>
                <th>Image</th>
            </tr>
        </thead>
        <tbody>
            {% for entertainer in entertainers %}
                <tr>
                    <td>{{ entertainer.id }}</td>
                    <td>{{ entertainer.title }}</td>
                    <td>{{ entertainer.desc_remove_underscore }}</td>
                    <td>{{ entertainer.init_cap_genre }}</td>
                    <td>{{ entertainer.init_cap_location }}</td>
                    <td>{{ entertainer.bio_summary }}<a href="{% url 'entertainer_profile' entertainer.id %}">...Read More</a></td>
                    <td><img src="{{ entertainer.profile_image.url }}" class="img-fluid center-block img-thumbnail" style="max-height:150px;"></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <hr>
    <div class="card-deck">
        {% for entertainer in entertainers %}
            <div class="card">
                <img class="card-img-top" src="{{ entertainer.profile_image.url }}" class="img-fluid center-block img-thumbnail" style="max-height:150px;" alt="Card image cap">
                <div class="card-body">
                    <h4 class="card-title">{{ entertainer.title }}</h4>
                    <p class="card-text">
                        {{ entertainer.bio_summary }}
                    </p>
                </div>
                <div class="card-footer">
                    <small class="text-muted"><a href="{% url 'entertainer_profile' entertainer.id %}">...Read More</a></small>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

entertainers/templates/entertainers/listings.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div id="listings-container">
        <div id="entertainer-header" class="page-header">
            <h2>Listed Entertainers</h2>
        <hr>
        </div>
        <div id="listing-menu" class="filtered">
            <div id="listing-row" class="row">
                <div id="filter-by-description" class="col-5 text-center">
                    <select id="description-select" class="styled-select orange semi-square"></select>
                </div>
                <div id="filter-by-location" class="col-5 text-center">
                    <select id="location-select" class="styled-select orange semi-square"></select>
                </div>
                <div class="col-2 text-center">
                    <button id="refine-button" class="btn-orange-no-hover">Refine Search</button>
                </div>
            </div>
            <div id="pagination" class="row">
                <div class="col-12 text-center">
                    <p>
                        Page: <span id="page_links"></span>
                    </p>
                </div>
            </div>
        </div>

        <div id="REST-data" class="card-deck row"></div>
    </div>

{% endblock %}
{% block script %}
    <script src="{% static "js/globals.js" %}"></script>
    <script src="{% static "js/talk_to_api.js" %}"></script>
    <script src="{% static "js/listing.js" %}"></script>
{% endblock %}