accounts/urls.py
from django.conf.urls import url
from . import views

# specific app URL pointable from template
app_name = 'accounts'

urlpatterns = [
    url(r'^register/', views.auth_register, name="register"),
    url(r'^login/', views.auth_login, name="login"),
    url(r'^logout/', views.auth_logout, name="logout"),
    url(r'^profile/', views.auth_profile, name="profile"),
]

entertainers/urls.py
from django.conf.urls import url
from . import views
from entertainers.views import EntertainerView

# specific app URL pointable from template
app_name = 'entertainers'

urlpatterns = [
    #   pages
    url(r'^listings/$', views.listings, name="listings"),
    url(r'^profile/(?P<entertainer_id>[0-9]+)/$', views.display_entertainer_profile, name="profile"),
    url(r'^create_profile/$', views.create_profile, name="create_profile"),
    #url(r'^edit_profile/(?P<pk>[0-9]+)$', views.edit_profile, name="edit_profile"),
    url(r'^edit_profile/(?P<pk>[0-9]+)$',views.edit_profile, name="edit_profile"),

    #   actions / voting
    url(r'^(?P<pk>[0-9]+)/like/', views.like, name="like"),
    url(r'^(?P<pk>[0-9]+)/dislike/', views.dislike, name="dislike"),

    #   URLS FOR REST API CLASS BASED VIEWS
    url(r'^api/listings/$', EntertainerView.as_view(), name="list_entertainers_api"),
    url(r'^api/listings/(?P<pk>[0-9]+)/$', EntertainerView.as_view(), name="update_entertainers_api"),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bookAnEntertainer</title>
    <!-- Required Bootstrap meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Book an Entertainer / Act / Musician / Band / Speaker / Comedian for your Event">
    <meta name="author" content="Cormac Liston">
    <!-- Required Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/font-awesome-4.7.0/css/font-awesome.css" %}">
    <link rel="stylesheet" href="{% static "css/custom.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
    {% block head_js %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-white">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Book an Entertainer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-md-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'entertainers:listings' %}" id="navbarDropdown" class="navbar_grey_a_href_orange text-right">
                            <i class="fa fa-search" aria-hidden="true"></i> Search
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMembers" class="navbar_grey_a_href_orange float-right" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMembers">
                            {% if user.is_active %}
                                <a class="dropdown-item nav-link navbar_grey_a_href_orange" href="{% url 'accounts:profile' %}" id="logged-in-">User: {{request.user.first_name}} {{request.user.last_name}}</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item nav-link" href="{% url 'accounts:logout' %}" class="navbar_grey_a_href_orange">Log Out</a>
                            {% else %}
                                <a class="dropdown-item nav-link" href="{% url 'accounts:login' %}" class="navbar_grey_a_href_orange">Login</a>
                                <a class="dropdown-item nav-link" href="{% url 'accounts:register' %}" class="navbar_grey_a_href_orange">Register</a>
                            {% endif %}
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <main>
        <section id="section1">
            <div class="container">
                {% if messages %}
                    <div class="alert alert-success">
                        <div class="messages">
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
                {% block content %}
                {% endblock %}
            </div>
        </section>
    </main>
    <footer>
        &nbsp;
    </footer>
    <!--<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <!--<script src="{% static "js/custom.js" %}"></script>-->
    {% block script %}{% endblock %}
</body>
</html>